# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands/commands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommands/commands.proto\x12\x08\x63ommands\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x11\x41\x64\x64\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\"\'\n\x14\x44\x65leteCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x85\x01\n\x13GetCommandsResponse\x12=\n\x08\x63ommands\x18\x01 \x03(\x0b\x32+.commands.GetCommandsResponse.CommandsEntry\x1a/\n\rCommandsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x15ImportCommandsRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"%\n\x15\x45xportCommandsRequest\x12\x0c\n\x04path\x18\x01 \x01(\t2\xf2\x02\n\x08\x43ommands\x12\x41\n\nAddCommand\x12\x1b.commands.AddCommandRequest\x1a\x16.google.protobuf.Empty\x12G\n\rDeleteCommand\x12\x1e.commands.DeleteCommandRequest\x1a\x16.google.protobuf.Empty\x12\x44\n\x0bGetCommands\x12\x16.google.protobuf.Empty\x1a\x1d.commands.GetCommandsResponse\x12I\n\x0eImportCommands\x12\x1f.commands.ImportCommandsRequest\x1a\x16.google.protobuf.Empty\x12I\n\x0e\x45xportCommands\x12\x1f.commands.ExportCommandsRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands.commands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._options = None
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._serialized_options = b'8\001'
  _ADDCOMMANDREQUEST._serialized_start=66
  _ADDCOMMANDREQUEST._serialized_end=118
  _DELETECOMMANDREQUEST._serialized_start=120
  _DELETECOMMANDREQUEST._serialized_end=159
  _GETCOMMANDSRESPONSE._serialized_start=162
  _GETCOMMANDSRESPONSE._serialized_end=295
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._serialized_start=248
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._serialized_end=295
  _IMPORTCOMMANDSREQUEST._serialized_start=297
  _IMPORTCOMMANDSREQUEST._serialized_end=334
  _EXPORTCOMMANDSREQUEST._serialized_start=336
  _EXPORTCOMMANDSREQUEST._serialized_end=373
  _COMMANDS._serialized_start=376
  _COMMANDS._serialized_end=746
# @@protoc_insertion_point(module_scope)
