audio:
  chunk_size: 2048
  channels: 1
  frequency: 16_000
  sample_format: 8 # port audio 16 bit int

model:
  path: "voice_models/russian/vosk-small-0.22"

virtual_keyboard:
  commands_path: "commands/commands.json"
  vk_codes_path: "config/vk_codes.json"
  similarity_threshold: 0.55

server:
  address: "localhost:50033"
