# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\x12\x08\x63ommands\x1a\x1bgoogle/protobuf/empty.proto\"4\n\x11\x41\x64\x64\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\"3\n\x12\x41\x64\x64\x43ommandResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\'\n\x14\x44\x65leteCommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"6\n\x15\x44\x65leteCommandResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\xa4\x01\n\x13GetCommandsResponse\x12=\n\x08\x63ommands\x18\x01 \x03(\x0b\x32+.commands.GetCommandsResponse.CommandsEntry\x12\x0e\n\x06status\x18\x02 \x01(\x03\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x1a/\n\rCommandsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xeb\x01\n\x08\x43ommands\x12G\n\nAddCommand\x12\x1b.commands.AddCommandRequest\x1a\x1c.commands.AddCommandResponse\x12P\n\rDeleteCommand\x12\x1e.commands.DeleteCommandRequest\x1a\x1f.commands.DeleteCommandResponse\x12\x44\n\x0bGetCommands\x12\x16.google.protobuf.Empty\x1a\x1d.commands.GetCommandsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._options = None
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._serialized_options = b'8\001'
  _ADDCOMMANDREQUEST._serialized_start=57
  _ADDCOMMANDREQUEST._serialized_end=109
  _ADDCOMMANDRESPONSE._serialized_start=111
  _ADDCOMMANDRESPONSE._serialized_end=162
  _DELETECOMMANDREQUEST._serialized_start=164
  _DELETECOMMANDREQUEST._serialized_end=203
  _DELETECOMMANDRESPONSE._serialized_start=205
  _DELETECOMMANDRESPONSE._serialized_end=259
  _GETCOMMANDSRESPONSE._serialized_start=262
  _GETCOMMANDSRESPONSE._serialized_end=426
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._serialized_start=379
  _GETCOMMANDSRESPONSE_COMMANDSENTRY._serialized_end=426
  _COMMANDS._serialized_start=429
  _COMMANDS._serialized_end=664
# @@protoc_insertion_point(module_scope)
