audio:
  chunk_size: 512
  channels: 1
  frequency: 16_000
  sample_format: 8 # port audio 16 bit int

model:
  path: "speech_to_text_models/russian/vosk-small-0.22"

virtual_keyboard:
  commands_path: "commands/commands.json"
  similarity_threshold: 0.55

server:
  address: "localhost:50033"

platform: "windows"
