# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_control.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x61pp_control.proto\x12\x0b\x61pp_control\"0\n\x0f\x44\x65\x66\x61ultResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"+\n\x1d\x43hangeMicrophoneStatusRequest\x12\n\n\x02on\x18\x01 \x01(\x08\x32p\n\nAppControl\x12\x62\n\x16\x43hangeMicrophoneStatus\x12*.app_control.ChangeMicrophoneStatusRequest\x1a\x1c.app_control.DefaultResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_control_pb2',
                                        globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _DEFAULTRESPONSE._serialized_start = 34
    _DEFAULTRESPONSE._serialized_end = 82
    _CHANGEMICROPHONESTATUSREQUEST._serialized_start = 84
    _CHANGEMICROPHONESTATUSREQUEST._serialized_end = 127
    _APPCONTROL._serialized_start = 129
    _APPCONTROL._serialized_end = 241
# @@protoc_insertion_point(module_scope)
