# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_control/app_control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pp_control/app_control.proto\x12\x0b\x61pp_control\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x1d\x43hangeMicrophoneStatusRequest\x12\n\n\x02on\x18\x01 \x01(\x08\x32j\n\nAppControl\x12\\\n\x16\x43hangeMicrophoneStatus\x12*.app_control.ChangeMicrophoneStatusRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_control.app_control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHANGEMICROPHONESTATUSREQUEST._serialized_start=75
  _CHANGEMICROPHONESTATUSREQUEST._serialized_end=118
  _APPCONTROL._serialized_start=120
  _APPCONTROL._serialized_end=226
# @@protoc_insertion_point(module_scope)
